export const backendEntities = {
  projects: [
    "id",
    "name",
    "clientName",
    "type",
    "status",
    "brandPrimary",
    "brandAccent",
    "createdAt",
    "topKpiLabel",
    "topKpiValue",
  ],
  teamMembers: ["id", "name", "email", "role", "avatarColor"],
  projectMembers: ["projectId", "memberId"],
  kpiSnapshots: ["id", "projectId", "metric", "current", "previous", "sparkline"],
  timeSeries: ["id", "projectId", "month", "traffic", "conversions", "spend", "leads"],
  channelBreakdowns: ["id", "projectId", "channel", "visits", "conversions", "spend", "costPerLead"],
  timelineAnnotations: ["id", "projectId", "date", "label", "note", "author"],
  goals: ["id", "projectId", "label", "targetValue", "currentValue", "unit", "period"],
  leads: [
    "id",
    "projectId",
    "name",
    "email",
    "company",
    "phone",
    "source",
    "status",
    "estimatedValue",
    "capturedFrom",
    "assignedTeamMember",
    "createdAt",
    "lastContactedAt",
  ],
  leadActivities: ["id", "leadId", "projectId", "activityType", "content", "author", "createdAt"],
  campaigns: [
    "id",
    "projectId",
    "name",
    "channel",
    "status",
    "startDate",
    "endDate",
    "budget",
    "spent",
    "impressions",
    "clicks",
    "conversions",
    "owner",
    "notes",
  ],
  tasks: ["id", "projectId", "title", "description", "column", "assignee", "dueDate", "priority", "notes"],
  calendarEvents: ["id", "projectId", "title", "channel", "date", "status", "assignee"],
  approvals: [
    "id",
    "projectId",
    "title",
    "type",
    "requestType",
    "thumbnailColor",
    "status",
    "submittedBy",
    "submittedAt",
    "summary",
    "details",
    "pros",
    "cons",
    "recommendation",
    "attachments",
  ],
  approvalComments: ["id", "approvalId", "author", "message", "createdAt"],
  reportConfigs: ["id", "projectId", "includedSections", "frequency", "internalReviewFirst", "lastSentAt", "engagementStats"],
  reportRecipients: ["reportConfigId", "email"],
  agencySettings: ["id", "agencyName", "logoPlaceholder", "notifications", "integrations", "updatedAt"],
};

export const backendEntityNames = Object.keys(backendEntities);
